import { useState, useEffect } from 'react';
import PageHeader from '../../../components/common/PageHeader';
import Card from '../../../components/common/Card';
import Button from '../../../components/common/Button';
import StatusBadge from '../../../components/common/StatusBadge';
import { fetchCarbonCreditsFromSupabase } from '../../carbonCredits/carbonCreditsService';

export default function CommunityCarbonCreditsPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('All');
  const [credits, setCredits] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    async function loadCredits() {
      setIsLoading(true);
      setError(null);
      try {
        const data = await fetchCarbonCreditsFromSupabase();
        setCredits(data);
      } catch (err) {
        setError('Failed to load carbon credits. Please try again.');
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    }
    loadCredits();
  }, []);

  const filteredCredits = credits.filter(c => {
    const matchesSearch = c.projectName?.toLowerCase().includes(searchTerm.toLowerCase()) || c.id?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'All' || c.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  const totalCredits = credits.reduce((acc, curr) => acc + (curr.quantity || 0), 0);
  const retiredCredits = credits.filter(c => c.status === 'Retired').reduce((acc, curr) => acc + (curr.quantity || 0), 0);
  const activeCredits = credits.filter(c => c.status === 'Available').reduce((acc, curr) => acc + (curr.quantity || 0), 0);

  return (
    <div className="flex flex-col w-full p-4 sm:p-6 lg:p-8 gap-6 max-w-[1600px] mx-auto font-body-md text-on-surface min-h-screen">
      <PageHeader 
        title="Carbon Credits" 
        subtitle="Track issued, transferred, and retired blue carbon credits generated by community projects."
      />

      {isLoading ? (
        <div className="flex items-center justify-center p-12">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>
      ) : error ? (
        <div className="p-4 bg-error/10 text-error rounded-xl border border-error/20">
          {error}
        </div>
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card accentTop="primary" className="flex flex-col gap-2 bg-[url('/grid-bg.svg')] bg-cover bg-center">
              <div className="flex justify-between items-start">
                <p className="font-label-md text-on-surface-variant uppercase font-semibold">Total Issued</p>
                <span className="material-symbols-outlined text-primary">psychiatry</span>
              </div>
              <div className="mt-2">
                <p className="font-headline-lg text-3xl font-bold text-primary">{totalCredits.toLocaleString()} <span className="text-sm font-normal text-on-surface-variant">tCO2e</span></p>
              </div>
            </Card>
            <Card accentTop="secondary" className="flex flex-col gap-2">
              <div className="flex justify-between items-start">
                <p className="font-label-md text-on-surface-variant uppercase font-semibold">Available to Trade</p>
                <span className="material-symbols-outlined text-secondary">swap_horiz</span>
              </div>
              <div className="mt-2">
                <p className="font-headline-lg text-3xl font-bold text-secondary">{activeCredits.toLocaleString()} <span className="text-sm font-normal text-on-surface-variant">tCO2e</span></p>
              </div>
            </Card>
            <Card accentTop="surface" className="flex flex-col gap-2 border-outline-variant/30">
              <div className="flex justify-between items-start">
                <p className="font-label-md text-on-surface-variant uppercase font-semibold">Total Retired</p>
                <span className="material-symbols-outlined text-on-surface-variant">done_all</span>
              </div>
              <div className="mt-2">
                <p className="font-headline-lg text-3xl font-bold text-on-surface">{retiredCredits.toLocaleString()} <span className="text-sm font-normal text-on-surface-variant">tCO2e</span></p>
              </div>
            </Card>
          </div>

          <Card>
            <div className="flex flex-col sm:flex-row gap-4 justify-between items-center mb-6">
              <h2 className="font-headline-md text-xl font-bold text-on-surface m-0">Credit Registry</h2>
              <div className="flex flex-col sm:flex-row gap-3 w-full sm:w-auto">
                <div className="relative flex-1 w-full sm:w-64">
                  <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span>
                  <input
                    type="text"
                    placeholder="Search ID or Project..."
                    className="w-full bg-surface-container-lowest border border-outline-variant/50 rounded-xl pl-10 pr-4 py-2 font-body-md text-on-surface focus:outline-none focus:ring-2 focus:ring-primary/20"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                  />
                </div>
                <select 
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="bg-surface-container-lowest border border-outline-variant/50 rounded-xl px-4 py-2 appearance-none focus:outline-none focus:ring-2 focus:ring-primary/20 font-body-md text-on-surface"
                >
                  <option value="All">All Status</option>
                  <option value="Available">Available</option>
                  <option value="Pending">Pending</option>
                  <option value="Transferred">Transferred</option>
                  <option value="Retired">Retired</option>
                </select>
              </div>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse min-w-[800px]">
                <thead>
                  <tr className="border-b border-outline-variant/30 text-on-surface-variant font-label-md uppercase tracking-wider text-xs">
                    <th className="pb-3 px-4 font-semibold">Token ID / Batch</th>
                    <th className="pb-3 px-4 font-semibold">Project</th>
                    <th className="pb-3 px-4 font-semibold">Quantity (tCO2e)</th>
                    <th className="pb-3 px-4 font-semibold">Issuance Date</th>
                    <th className="pb-3 px-4 font-semibold">Status</th>
                    <th className="pb-3 px-4 font-semibold">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-outline-variant/20">
                  {filteredCredits.map((credit, i) => (
                    <tr key={credit.id || i} className="hover:bg-surface-container-low/50 transition-colors">
                      <td className="py-4 px-4">
                        <div className="flex flex-col gap-0.5">
                          <span className="font-mono-data font-semibold text-primary">{credit.id}</span>
                          <span className="text-[10px] text-on-surface-variant uppercase truncate max-w-[120px]" title={credit.vintage || 'N/A'}>Vintage: {credit.vintage || 'N/A'}</span>
                        </div>
                      </td>
                      <td className="py-4 px-4 font-title-md font-semibold text-on-surface">{credit.projectName}</td>
                      <td className="py-4 px-4 font-mono-data font-bold text-on-surface">{credit.quantity?.toLocaleString() || 0}</td>
                      <td className="py-4 px-4 font-mono-data text-sm text-on-surface-variant">{credit.issueDate || credit.createdAt?.split('T')[0] || 'N/A'}</td>
                      <td className="py-4 px-4">
                        <StatusBadge status={credit.status} />
                      </td>
                      <td className="py-4 px-4">
                        <Button variant="outline" size="sm" onClick={() => window.open(`https://explorer.polygon.technology/tx/${credit.id}`, '_blank')}>
                          View on Ledger
                        </Button>
                      </td>
                    </tr>
                  ))}
                  {filteredCredits.length === 0 && (
                    <tr>
                      <td colSpan="6" className="py-8 text-center text-on-surface-variant">
                        No credits found matching filters.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </Card>
        </>
      )}
    </div>
  );
}
