export const publicRegistryProjects = [
  {
    id: 'PRJ-2023-089',
    name: 'Maharashtra Mangrove Restoration',
    location: 'Ratnagiri, Maharashtra, India',
    country: 'in',
    countryName: 'India',
    region: 'South Asia',
    type: 'Mangrove',
    estYear: '2021',
    developer: 'EcoTrust India',
    developerRole: 'Project Developer',
    status: 'Verified Active',
    statusCategory: 'verified',
    totalSequestered: '14.2k',
    totalSequesteredNum: 14200,
    areaCoverage: '128',
    areaCoverageHa: 128,
    creditPrice: 28,
    priceDisplay: '$28 / tCO2e',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=800',
    coordinates: { lat: 16.9902, lng: 73.312 },
    mapPosition: { top: '48%', left: '46%' },
    description: 'Coastal mangrove restoration and blue carbon sequestration in Ratnagiri sector.',
    ledgerTimeline: [
      {
        id: 'L-11',
        title: 'Credit Batch Minted',
        date: 'Nov 01, 2023',
        description: 'Verified carbon credits minted to smart contract.',
        txHash: '0x9e2b4d7c0f1a3b5e7d9c1b3a5f7e9d1c810427bc',
        txShort: 'Tx: 0x9e2b...27bc',
        active: true,
      },
      {
        id: 'L-12',
        title: 'MRV Baseline Validated',
        date: 'Oct 28, 2023',
        description: 'NCCR independent audit passed with zero non-conformances.',
        txHash: '0x7a3f8b2ec049281a029384712039847120398b2e',
        txShort: 'Tx: 0x7a3f...8b2e',
        active: false,
      },
    ],
  },
  {
    id: 'PRJ-2023-156',
    name: 'Kutch Tidal Flats',
    location: 'Kutch, Gujarat, India',
    country: 'in',
    countryName: 'India',
    region: 'South Asia',
    type: 'Salt Marsh',
    estYear: '2022',
    developer: 'Gujarat Ecology Commission',
    developerRole: 'Project Developer',
    status: 'In Review',
    statusCategory: 'pending',
    totalSequestered: '22.1k',
    totalSequesteredNum: 22100,
    areaCoverage: '512',
    areaCoverageHa: 512,
    creditPrice: 24,
    priceDisplay: '$24 / tCO2e',
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800',
    coordinates: { lat: 23.7337, lng: 69.8597 },
    mapPosition: { top: '35%', left: '42%' },
    description: 'Intertidal salt marsh and mangrove expansion along the Gulf of Kutch coastline.',
    ledgerTimeline: [],
  },
  {
    id: 'PRJ-2023-201',
    name: 'Sundarbans West Reserve',
    location: 'South 24 Parganas, West Bengal, India',
    country: 'in',
    countryName: 'India',
    region: 'South Asia',
    type: 'Mangrove',
    estYear: '2023',
    developer: 'Sundarbans Forest Dept',
    developerRole: 'Project Developer',
    status: 'Active',
    statusCategory: 'registered',
    totalSequestered: '45.0k',
    totalSequesteredNum: 45000,
    areaCoverage: '340',
    areaCoverageHa: 340,
    creditPrice: 30,
    priceDisplay: '$30 / tCO2e',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800',
    coordinates: { lat: 21.9497, lng: 88.9002 },
    mapPosition: { top: '50%', left: '60%' },
    description: 'Deep mangrove estuary conservation with strict biodiversity protection buffers.',
    ledgerTimeline: [],
  },
];
